version: '3.8'

services:
  web:
    # Dockerfileがあるカレントディレクトリをビルドコンテキストとして使用
    build: .
    # コンテナのポート5000をホストのポート5000にマッピング
    ports:
      - "5000:5000"
    # ソースコードの変更をコンテナに即時反映させるためのボリュームマウント
    # ホストのカレントディレクトリをコンテナの/appにマウント
    volumes:
      - .:/app
    # 環境変数
    environment:
      - FLASK_ENV=development
      # ここに取得したNewsAPIのキーを設定
      - NEWS_API_KEY=37ea12f90efa480393cae46c48cd0475
